### ISSUE TITLE
Compilation failure on V14

### ISSUE THREAD

**Issue by samie** [TatuLund/TabSheet#2]
When using the component v 0.1.0 from Directory the following compilation error happens with Vaadin 14.8.13:
```
[webpack] ERROR dev-webpack - ERROR in /project/node_modules/@vaadin/flow-frontend/tab-sheet.ts
[webpack] ERROR dev-webpack - ../node_modules/@vaadin/flow-frontend/tab-sheet.ts
[webpack] ERROR dev-webpack - [tsl] ERROR in /project/node_modules/@vaadin/flow-frontend/tab-sheet.ts(205,13)
[webpack] ERROR dev-webpack -       TS6133: 'theme' is declared but its value is never read.
[webpack] ERROR dev-webpack - ? ?wdm?: Failed to compile.
```

Using version 1.6.0 gives the following frontend compilation error with Vaadin 14.8.13:

```
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/tab-sheet.ts
[webpack] ERROR dev-webpack - Module not found: Error: Can't resolve '@vaadin/vaadin-icon' in '/project/node_modules/@vaadin/flow-frontend'
[webpack] ERROR dev-webpack -  @ ../node_modules/@vaadin/flow-frontend/tab-sheet.ts 8:0-29
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/tab-sheet.ts
```

**Comment by TatuLund** [comment]
> When using the component v 0.1.0 from Directory the following compilation error happens with Vaadin 14.8.13

Does not prevent of working, as the function is not used due missing themable mixing support /w Lit in Vaadin 14 framework itself, but NOP version of the function is required anyway.

> Using version 1.6.0 gives the following frontend compilation error with Vaadin 14.8.13:

1.6.0 is not even supposed to work with 14.8.13

**Comment by TatuLund** [comment]
Furthermore, the default "tsconfig.json" generated by Vaadin has this setting, which says the compiler should not fail if function parameter is unused. 

```
{
  "compilerOptions": {
     "noUnusedParameters": false,
      ...
  }
} 
```

**Comment by TatuLund** [comment]
Fixed in v0.1.1 anyway.

**Comment by samie** [comment]
Thanks! Works nicely now. This was an important first impression fix.
